"""initial schema

Revision ID: 62214ff70af8
Revises: 
Create Date: 2026-04-28 04:45:54.706394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62214ff70af8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_extraction_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('billable_count', sa.Integer(), nullable=False),
    sa.Column('charged_count', sa.Integer(), nullable=False),
    sa.Column('cost_this_request', sa.Float(), nullable=False),
    sa.Column('total_cost_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_extraction_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_extraction_usage_logs_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_extraction_usage_logs_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_extraction_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_extraction_usage_logs_username'))
        batch_op.drop_index(batch_op.f('ix_email_extraction_usage_logs_request_id'))

    op.drop_table('email_extraction_usage_logs')
    # ### end Alembic commands ###
